//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public students()
        {
            this.student_type = new HashSet<student_type>();
        }
    
        public int id { get; set; }
        public string family_name { get; set; }
        public string first_name { get; set; }
        public int @class { get; set; }
        public Nullable<int> chat { get; set; }
        public Nullable<int> rec_row { get; set; }
        public Nullable<int> col { get; set; }
        public Nullable<int> line { get; set; }
    
        public virtual @class class1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student_type> student_type { get; set; }
    }
}
